# Generated by Django 5.1.6 on 2025-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderclass_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclass',
            name='lookup_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
