# Generated by Django 5.1.6 on 2025-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='code',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='name',
            new_name='status_name',
        ),
    ]
