# Generated by Django 5.1.6 on 2025-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_code_orderstatus_lookup_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='type_name',
            field=models.CharField(max_length=50),
        ),
    ]
