# Generated by Django 5.1.6 on 2025-02-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_remove_project_enterprise_client_project_client_and_more'),
        ('users', '0003_customuser_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='enterprise.project'),
        ),
    ]
