# Generated by Django 5.1.6 on 2025-02-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project',
        ),
    ]
