# Generated by Django 5.1.6 on 2025-02-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
    ]
