# Generated by Django 5.1.6 on 2025-02-25 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='license_plate_id',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
